---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec:
  activeDeadlineSeconds: 2
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: rootroot
      volumeMounts:
        - name: myvol
          mountPath: /var/lib/mysql
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: myvol-pvc
      