---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  minReadySeconds: 2
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        version: "1.23"
    spec:
      containers:
        - name: nginx-deployment
          image: nginx
          ports:
            - containerPort: 80