---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-vol
      persistentVolumeClaim:
        claimName: pvc-vol