---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-deploy
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app: dashboard
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: dashboard-pod
      labels:
        app: dashboard
    spec:
      activeDeadlineSeconds: 2
      containers:
        - name: dashboard
          image: shaikkhajaibrahim/dashboardservice:1.0.0
          ports:
            - containerPort: 80  