---
apiVersion: v1
kind: Pod
metadata:
  name: restartalways
  labels:
    app: alpine
    env: prod
spec:
  activeDeadlineSeconds: 2
  restartPolicy: Always
  containers:
    - name: always
      image: alpine
      args:
        - sleep
        - 10s