---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins-rs1
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
          livenessProbe:
            exec:
              command:
                - pwd
          readinessProbe:
            httpGet:
              path: /
              port: 80