---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql:8
      envFrom:
        - configMapKeyRef:
            name: configmap-mysql
            optional: false
      ports:
        containerPort: 3306