---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basket
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: id-pod1
      labels:
        app: basket
    spec:
      containers:
        - name: basket
          image: shaikkhajaibrahim/dummy-basket-srv:1.0.0
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-deploy1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: id-pod2
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: shaikkhajaibrahim/dummy-ctlg-srv:1.0.0
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-deploy2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: id-pod3
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: shaikkhajaibrahim/dummy-ord-srv:1.0.0
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-deploy3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: identity
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: id-pod4
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: shaikkhajaibrahim/dummy-id-srv:1.0.0
          ports:
            - containerPort: 80  