---
apiVersion: v1
kind: Service
metadata:
  name: microservice-svc
spec:
  selector:
    app: basket
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-svc
spec:
  selector:
    app: ctlg
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-svc
spec:
  selector:
    app: order
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-svc
spec:
  selector:
    app: id
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80