---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
spec:
  minReadySeconds: 2
  replicas: 4
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins4
      labels:
        app: jenkins
    spec:
      activeDeadlineSeconds: 2
      restartPolicy: OnFailure
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk11
          ports:
            - name: jenkins
              containerPort: 8080        