---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: periodicjob
  labels:
    app: alpine3
    env: prod
spec:
  schedule: '* * * * *'
  jobTemplate:
    metadata:
      name: cronjob1
    spec:
      backoffLimit: 4
      template:
        metadata:
          name: cron
        spec:
          restartPolicy: OnFailure
          containers:
            - name: alpine
              image: alpine
              args:
                - sleep
                - 5s
