---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
  labels:
    app: alpine
    env: testing
spec:
  activeDeadlineSeconds: 5
  template:
    metadata:
      name: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job1
          image: alpine
          args:
            - sleep
            - 5s