---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: jenkinsandalpine-rs
      port: 30000
      targetPort: 8080