---
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    metadata:
      name: myjob
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alpine
          image: alpine
          args:
            - sleep
            - 20s
          