---
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      name: myjob
      labels:
        app: alpine
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alpine
          image: alpine
          args:
            - sleep
            - 20s
          