---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  containers:
    - name: alpine
      image: alpine
      command:
        - sleep
        - 1d
      envFrom:
        - configMapRef:
            name: dummy-configmap
            optional: false