---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
      envFrom:
        - secretKeyRef:
            name: mysql-secret
            optional: false